---
- name: task for slave2
  hosts: slave2
  become: true
  tasks:
  - name: install apache2 in slave2
    apt: name=apache2 state=latest
  - name: Deploy static website
    copy: src=index.html dest=/var/www/html/
